#!/bin/bash
# Queue wait stats from ~/boar/heavy.log ([heavyq] lines) for the last N minutes (default 60).
mins=${1:-60}; since=$(date -v-"${mins}"M "+%F %T")
awk -v since="$since" '$1=="[heavyq]" && ($2" "$3) >= since && /START waited=/ {
  match($0, /waited=[0-9]+/); w = substr($0, RSTART + 7, RLENGTH - 7) + 0
  n++; s += w; if (w > m) m = w
} END {
  if (n) printf "jobs started: %d  wait avg: %ds  max: %ds  (since %s)\n", n, s / n, m, since
  else print "no jobs started since " since
}' ~/boar/heavy.log
