/**
 * Catalog of offline places packs (scripts/build-poi-pack.mjs), one per
 * region, and the pure helpers the UI uses to suggest one. No native imports.
 *
 * The entries below are the SAMPLE build of 2026-09-26: five metropolitan
 * areas picked by hand and five drawn at random (scripts/draw-poi-cities.mjs,
 * seed 20261003), generated from each pack's .json summary: sizes, SHA-256 and counts
 * are measured, not estimated. `sourceUrl` is the file on the Hugging Face
 * dataset r4topunk/boar-packs, pinned to the commit it was uploaded in.
 */
import type { CatalogModel } from "../models/manifest";
import { registerAssetProvider } from "../models/assetRegistry";

export interface PoiRegion {
  id: string;
  name: { en: string; pt: string };
  sizeBytes: number;
  sha256: string;
  /** Empty until the pack is hosted. */
  sourceUrl: string;
  /** Relative to the app's documents directory. */
  filename: string;
  /** OSM places with a name plus Wikivoyage Eat/Drink listings. */
  poiCount: number;
  /** Places tagged diet:vegan (yes/only/limited) or cuisine=vegan. */
  veganCount: number;
  vegetarianCount: number;
  /** The region's biggest places (GeoNames) and how many food POIs lie within ~5 km of each. */
  cities: Array<{ name: string; lat: number; lon: number; pois: number }>;
  /** [minLat, minLon, maxLat, maxLon] */
  bbox: [number, number, number, number];
  timeZones: string[];
  /** OSM replication timestamp of the data. */
  osmDate: string;
  builtAt: string;
}

export const POI_LICENSE = "ODbL 1.0 (© OpenStreetMap contributors) + CC BY-SA 4.0 (Wikivoyage)";

/** Catalog id of the world gazetteer; every places pack requires it. */
export const WORLD_PLACES_ID = "poi-world-places";

/**
 * The world gazetteer used to resolve place names ("restaurants in Lisbon"), shipped with any places pack.
 * Carries the tile index (table tiles: 2,999 1° tiles, URLs pinned to HF commit c56c09b), phase 1 of the world tiles.
 */
export const WORLD_PLACES = {
  filename: "poi/world-places.sqlite",
  sizeBytes: 21585920,
  sha256: "b6771c536efe9b61bff283d4ceadca89c0c4c76e0ec9412f9a0cc981c48b0d15",
  license: "CC BY 4.0 (GeoNames)",
  sourceUrl: "https://huggingface.co/datasets/r4topunk/boar-packs/resolve/584bd17a8c76260e0a96fe425e0b847597a4b02b/places/world-places.sqlite",
  places: 34149,
};

// <generated by scripts/poi-regions-catalog.mjs>
export const POI_REGIONS: PoiRegion[] = [
  {
    id: "sao-paulo",
    name: {
      en: "São Paulo",
      pt: "São Paulo"
    },
    sizeBytes: 1380352,
    sha256: "42e6caf31e9018ad76e282f26114812dbdf0ab23c2aaf269199b9126bbe935d3",
    sourceUrl: "https://huggingface.co/datasets/r4topunk/boar-packs/resolve/2b5b193b8fbd9f69dcf0af4447fa324066904a4f/places/cities/sao-paulo.sqlite",
    filename: "poi/sao-paulo.sqlite",
    poiCount: 7013,
    veganCount: 126,
    vegetarianCount: 105,
    cities: [
      {
        name: "São Paulo",
        lat: -23.5475,
        lon: -46.6361,
        pois: 2785
      },
      {
        name: "Guarulhos",
        lat: -23.4628,
        lon: -46.5333,
        pois: 222
      },
      {
        name: "São Bernardo do Campo",
        lat: -23.6939,
        lon: -46.565,
        pois: 785
      },
      {
        name: "Osasco",
        lat: -23.5325,
        lon: -46.7917,
        pois: 147
      },
      {
        name: "Santo André",
        lat: -23.6639,
        lon: -46.5383,
        pois: 806
      },
      {
        name: "Mauá",
        lat: -23.6678,
        lon: -46.4614,
        pois: 124
      },
      {
        name: "Diadema",
        lat: -23.6861,
        lon: -46.6228,
        pois: 241
      },
      {
        name: "Grajaú",
        lat: -23.7698,
        lon: -46.6711,
        pois: 25
      },
      {
        name: "Jardim Angela",
        lat: -23.7164,
        lon: -46.7687,
        pois: 80
      },
      {
        name: "Taboão da Serra",
        lat: -23.6261,
        lon: -46.7917,
        pois: 105
      }
    ],
    bbox: [
      -23.8,
      -46.83,
      -23.36,
      -46.36
    ],
    timeZones: [
      "America/Sao_Paulo"
    ],
    osmDate: "2026-09-26T20:23:48Z",
    builtAt: "2026-09-26T21:31:50.197Z"
  },
  {
    id: "singapore",
    name: {
      en: "Singapore",
      pt: "Singapura"
    },
    sizeBytes: 1863680,
    sha256: "bd7c1afcb59f4438bb2a9b0fbde2360720194ea05ac5081ee9dc4fed0c094506",
    sourceUrl: "https://huggingface.co/datasets/r4topunk/boar-packs/resolve/2b5b193b8fbd9f69dcf0af4447fa324066904a4f/places/cities/singapore.sqlite",
    filename: "poi/singapore.sqlite",
    poiCount: 10188,
    veganCount: 97,
    vegetarianCount: 277,
    cities: [
      {
        name: "Singapore",
        lat: 1.2897,
        lon: 103.8501,
        pois: 5287
      },
      {
        name: "Johor Bahru",
        lat: 1.4655,
        lon: 103.7578,
        pois: 392
      },
      {
        name: "Iskandar Puteri",
        lat: 1.3932,
        lon: 103.6232,
        pois: 99
      },
      {
        name: "Pasir Gudang",
        lat: 1.462,
        lon: 103.9053,
        pois: 79
      },
      {
        name: "Bedok New Town",
        lat: 1.3264,
        lon: 103.9417,
        pois: 1429
      },
      {
        name: "Ulu Bedok",
        lat: 1.3333,
        lon: 103.9333,
        pois: 1578
      },
      {
        name: "Sengkang New Town",
        lat: 1.3917,
        lon: 103.8944,
        pois: 1132
      },
      {
        name: "Tampines Estate",
        lat: 1.3581,
        lon: 103.9403,
        pois: 1542
      },
      {
        name: "Jurong Town",
        lat: 1.3342,
        lon: 103.7228,
        pois: 821
      },
      {
        name: "Tampines New Town",
        lat: 1.3492,
        lon: 103.9497,
        pois: 1273
      }
    ],
    bbox: [
      1.16,
      103.59,
      1.48,
      104.1
    ],
    timeZones: [
      "Asia/Singapore"
    ],
    osmDate: "2026-09-26T20:24:49Z",
    builtAt: "2026-09-26T21:32:02.093Z"
  },
  {
    id: "taipei",
    name: {
      en: "Taipei",
      pt: "Taipé"
    },
    sizeBytes: 3366912,
    sha256: "0831d93f747e4fa002d850523fc4098bc58ee262058b8b54b6a0b3cc60f5f480",
    sourceUrl: "https://huggingface.co/datasets/r4topunk/boar-packs/resolve/2b5b193b8fbd9f69dcf0af4447fa324066904a4f/places/cities/taipei.sqlite",
    filename: "poi/taipei.sqlite",
    poiCount: 18857,
    veganCount: 156,
    vegetarianCount: 407,
    cities: [
      {
        name: "Taipei",
        lat: 25.0531,
        lon: 121.5264,
        pois: 11828
      },
      {
        name: "New Taipei City",
        lat: 25.062,
        lon: 121.457,
        pois: 2768
      },
      {
        name: "Banqiao",
        lat: 25.0143,
        lon: 121.4672,
        pois: 4189
      },
      {
        name: "Neihu",
        lat: 25.0815,
        lon: 121.5881,
        pois: 5247
      },
      {
        name: "Xizhi",
        lat: 25.0662,
        lon: 121.6599,
        pois: 627
      }
    ],
    bbox: [
      24.96,
      121.45,
      25.21,
      121.67
    ],
    timeZones: [
      "Asia/Taipei"
    ],
    osmDate: "2026-09-26T20:24:49Z",
    builtAt: "2026-09-26T21:32:13.671Z"
  },
  {
    id: "buenos-aires",
    name: {
      en: "Buenos Aires",
      pt: "Buenos Aires"
    },
    sizeBytes: 1482752,
    sha256: "dedc896e659e112e16811005d038bd9cff6ead678b8d63b566565eec67ca8b73",
    sourceUrl: "https://huggingface.co/datasets/r4topunk/boar-packs/resolve/2b5b193b8fbd9f69dcf0af4447fa324066904a4f/places/cities/buenos-aires.sqlite",
    filename: "poi/buenos-aires.sqlite",
    poiCount: 8049,
    veganCount: 78,
    vegetarianCount: 104,
    cities: [
      {
        name: "Buenos Aires",
        lat: -34.6131,
        lon: -58.3772,
        pois: 3265
      },
      {
        name: "Avellaneda",
        lat: -34.6602,
        lon: -58.3674,
        pois: 1081
      },
      {
        name: "Palermo",
        lat: -34.5886,
        lon: -58.4305,
        pois: 5068
      },
      {
        name: "Lanús",
        lat: -34.7076,
        lon: -58.3913,
        pois: 250
      },
      {
        name: "Balvanera",
        lat: -34.6103,
        lon: -58.3977,
        pois: 4468
      },
      {
        name: "Belgrano",
        lat: -34.5627,
        lon: -58.4583,
        pois: 3749
      },
      {
        name: "Villa Lugano",
        lat: -34.6791,
        lon: -58.4726,
        pois: 515
      },
      {
        name: "Barracas",
        lat: -34.6497,
        lon: -58.3834,
        pois: 1991
      },
      {
        name: "Sarandí",
        lat: -34.6816,
        lon: -58.3464,
        pois: 282
      },
      {
        name: "Colegiales",
        lat: -34.5737,
        lon: -58.4492,
        pois: 4332
      }
    ],
    bbox: [
      -34.71,
      -58.54,
      -34.52,
      -58.33
    ],
    timeZones: [
      "America/Argentina/Buenos_Aires"
    ],
    osmDate: "2026-09-26T20:25:56Z",
    builtAt: "2026-09-26T21:32:25.251Z"
  },
  {
    id: "berlin",
    name: {
      en: "Berlin",
      pt: "Berlim"
    },
    sizeBytes: 3309568,
    sha256: "9216b3b0e55eb435390c79fc9460b99bc60d4396520091a8e37c22155e3c7ba3",
    sourceUrl: "https://huggingface.co/datasets/r4topunk/boar-packs/resolve/2b5b193b8fbd9f69dcf0af4447fa324066904a4f/places/cities/berlin.sqlite",
    filename: "poi/berlin.sqlite",
    poiCount: 15278,
    veganCount: 1979,
    vegetarianCount: 3437,
    cities: [
      {
        name: "Berlin",
        lat: 52.5244,
        lon: 13.4105,
        pois: 5993
      },
      {
        name: "Neukölln",
        lat: 52.4772,
        lon: 13.4313,
        pois: 4365
      },
      {
        name: "Kreuzberg",
        lat: 52.4997,
        lon: 13.4034,
        pois: 5867
      },
      {
        name: "Prenzlauer Berg",
        lat: 52.5388,
        lon: 13.4244,
        pois: 5227
      },
      {
        name: "Charlottenburg",
        lat: 52.5167,
        lon: 13.2833,
        pois: 2016
      },
      {
        name: "Schöneberg",
        lat: 52.498,
        lon: 13.3443,
        pois: 4649
      },
      {
        name: "Friedrichshain",
        lat: 52.5156,
        lon: 13.4548,
        pois: 4555
      },
      {
        name: "Marzahn",
        lat: 52.5453,
        lon: 13.5698,
        pois: 333
      },
      {
        name: "Mitte",
        lat: 52.52,
        lon: 13.4049,
        pois: 6083
      },
      {
        name: "Wilmersdorf",
        lat: 52.4833,
        lon: 13.3167,
        pois: 3530
      }
    ],
    bbox: [
      52.33,
      13.08,
      52.68,
      13.77
    ],
    timeZones: [
      "Europe/Berlin"
    ],
    osmDate: "2026-09-26T20:27:59Z",
    builtAt: "2026-09-26T21:32:37.864Z"
  },
  {
    id: "edmonton",
    name: {
      en: "Edmonton",
      pt: "Edmonton"
    },
    sizeBytes: 552960,
    sha256: "76ad021e7048813c4eab394689c97c78123ea5e1bfed73e7b95cc162a6f8cb4c",
    sourceUrl: "https://huggingface.co/datasets/r4topunk/boar-packs/resolve/2b5b193b8fbd9f69dcf0af4447fa324066904a4f/places/cities/edmonton.sqlite",
    filename: "poi/edmonton.sqlite",
    poiCount: 2520,
    veganCount: 12,
    vegetarianCount: 16,
    cities: [
      {
        name: "Edmonton",
        lat: 53.5501,
        lon: -113.4687,
        pois: 688
      },
      {
        name: "Sherwood Park",
        lat: 53.5168,
        lon: -113.3187,
        pois: 154
      },
      {
        name: "St. Albert",
        lat: 53.6334,
        lon: -113.6353,
        pois: 144
      },
      {
        name: "Wîhkwêntôwin",
        lat: 53.5431,
        lon: -113.5222,
        pois: 777
      }
    ],
    bbox: [
      53.37,
      -113.77,
      53.73,
      -113.17
    ],
    timeZones: [
      "America/Edmonton"
    ],
    osmDate: "2026-09-26T22:35:51Z",
    builtAt: "2026-09-26T22:42:52.012Z"
  },
  {
    id: "qujing",
    name: {
      en: "Qujing",
      pt: "Qujing"
    },
    sizeBytes: 36864,
    sha256: "17a462c6eba34d34a7011295799e3e7372b7a3e44fadf5f9fe7152298e126443",
    sourceUrl: "https://huggingface.co/datasets/r4topunk/boar-packs/resolve/2b5b193b8fbd9f69dcf0af4447fa324066904a4f/places/cities/qujing.sqlite",
    filename: "poi/qujing.sqlite",
    poiCount: 3,
    veganCount: 0,
    vegetarianCount: 0,
    cities: [
      {
        name: "Qujing",
        lat: 25.4833,
        lon: 103.7833,
        pois: 0
      }
    ],
    bbox: [
      25.3,
      103.58,
      25.66,
      103.98
    ],
    timeZones: [
      "Asia/Shanghai"
    ],
    osmDate: "2026-09-26T22:35:51Z",
    builtAt: "2026-09-26T22:43:15.855Z"
  },
  {
    id: "queens",
    name: {
      en: "Queens",
      pt: "Queens"
    },
    sizeBytes: 4292608,
    sha256: "00e0239a7f0aa7e9671607adb8c2893f84eeef94ad1e5e453b65db7b7c9c3f0a",
    sourceUrl: "https://huggingface.co/datasets/r4topunk/boar-packs/resolve/2b5b193b8fbd9f69dcf0af4447fa324066904a4f/places/cities/queens.sqlite",
    filename: "poi/queens.sqlite",
    poiCount: 20011,
    veganCount: 665,
    vegetarianCount: 837,
    cities: [
      {
        name: "New York City",
        lat: 40.7143,
        lon: -74.006,
        pois: 8090
      },
      {
        name: "Brooklyn",
        lat: 40.6501,
        lon: -73.9496,
        pois: 2936
      },
      {
        name: "Queens",
        lat: 40.6815,
        lon: -73.8365,
        pois: 1088
      },
      {
        name: "Manhattan",
        lat: 40.7834,
        lon: -73.9663,
        pois: 5824
      },
      {
        name: "The Bronx",
        lat: 40.8499,
        lon: -73.8664,
        pois: 316
      },
      {
        name: "Upper West Side",
        lat: 40.7871,
        lon: -73.9754,
        pois: 5142
      },
      {
        name: "Jamaica",
        lat: 40.6915,
        lon: -73.8057,
        pois: 1184
      },
      {
        name: "East Flatbush",
        lat: 40.6537,
        lon: -73.9304,
        pois: 2179
      },
      {
        name: "East New York",
        lat: 40.6668,
        lon: -73.8824,
        pois: 1244
      },
      {
        name: "Washington Heights",
        lat: 40.8501,
        lon: -73.9354,
        pois: 825
      }
    ],
    bbox: [
      40.5,
      -74.07,
      40.86,
      -73.6
    ],
    timeZones: [
      "America/New_York"
    ],
    osmDate: "2026-09-26T22:37:50Z",
    builtAt: "2026-09-26T22:43:29.773Z"
  },
  {
    id: "bien-hoa",
    name: {
      en: "Biên Hòa",
      pt: "Biên Hòa"
    },
    sizeBytes: 614400,
    sha256: "d9ce786f500286ac56584b06c4ba01c1d092254ded8d0e78c475d861540318d3",
    sourceUrl: "https://huggingface.co/datasets/r4topunk/boar-packs/resolve/2b5b193b8fbd9f69dcf0af4447fa324066904a4f/places/cities/bien-hoa.sqlite",
    filename: "poi/bien-hoa.sqlite",
    poiCount: 3206,
    veganCount: 266,
    vegetarianCount: 305,
    cities: [
      {
        name: "Biên Hòa",
        lat: 10.9447,
        lon: 106.8243,
        pois: 93
      },
      {
        name: "Thuận An",
        lat: 10.9239,
        lon: 106.7143,
        pois: 34
      },
      {
        name: "Bình Thạnh",
        lat: 10.811,
        lon: 106.706,
        pois: 2582
      },
      {
        name: "Thủ Đức",
        lat: 10.8486,
        lon: 106.7721,
        pois: 402
      },
      {
        name: "Dĩ An",
        lat: 10.9068,
        lon: 106.7694,
        pois: 122
      },
      {
        name: "Quận Mười",
        lat: 10.7682,
        lon: 106.6663,
        pois: 2177
      },
      {
        name: "Thủ Dầu Một",
        lat: 10.9804,
        lon: 106.6519,
        pois: 53
      },
      {
        name: "Quận Mười Một",
        lat: 10.7638,
        lon: 106.6436,
        pois: 1152
      },
      {
        name: "Quận Ba",
        lat: 10.7749,
        lon: 106.6863,
        pois: 2398
      },
      {
        name: "Quận Bốn",
        lat: 10.7668,
        lon: 106.7057,
        pois: 2396
      }
    ],
    bbox: [
      10.76,
      106.64,
      11.12,
      107.01
    ],
    timeZones: [
      "Asia/Ho_Chi_Minh"
    ],
    osmDate: "2026-09-26T22:39:54Z",
    builtAt: "2026-09-26T22:43:42.292Z"
  },
  {
    id: "ciudad-nezahualcoyotl",
    name: {
      en: "Ciudad Nezahualcoyotl",
      pt: "Ciudad Nezahualcoyotl"
    },
    sizeBytes: 1036288,
    sha256: "7c0818b511f504a4bd824dd069b54d32445ddcf36200d1bc5dff54dbf08f2a6a",
    sourceUrl: "https://huggingface.co/datasets/r4topunk/boar-packs/resolve/2b5b193b8fbd9f69dcf0af4447fa324066904a4f/places/cities/ciudad-nezahualcoyotl.sqlite",
    filename: "poi/ciudad-nezahualcoyotl.sqlite",
    poiCount: 6098,
    veganCount: 60,
    vegetarianCount: 56,
    cities: [
      {
        name: "Mexico City",
        lat: 19.4285,
        lon: -99.1277,
        pois: 2957
      },
      {
        name: "Iztapalapa",
        lat: 19.3553,
        lon: -99.0622,
        pois: 329
      },
      {
        name: "Gustavo Adolfo Madero",
        lat: 19.4939,
        lon: -99.1107,
        pois: 625
      },
      {
        name: "Ciudad Nezahualcoyotl",
        lat: 19.4006,
        lon: -99.0148,
        pois: 90
      },
      {
        name: "Álvaro Obregón",
        lat: 19.3587,
        lon: -99.2033,
        pois: 1304
      },
      {
        name: "Tlalnepantla",
        lat: 19.5401,
        lon: -99.1954,
        pois: 119
      },
      {
        name: "Coyoacán",
        lat: 19.3467,
        lon: -99.1617,
        pois: 1679
      },
      {
        name: "Tlalpan",
        lat: 19.2951,
        lon: -99.1621,
        pois: 702
      },
      {
        name: "Cuauhtémoc",
        lat: 19.4451,
        lon: -99.1461,
        pois: 2919
      },
      {
        name: "Xochimilco",
        lat: 19.2547,
        lon: -99.1036,
        pois: 203
      }
    ],
    bbox: [
      19.22,
      -99.21,
      19.58,
      -98.82
    ],
    timeZones: [
      "America/Mexico_City"
    ],
    osmDate: "2026-09-26T22:39:54Z",
    builtAt: "2026-09-26T22:43:53.860Z"
  }
];
// </generated>

function area([minLat, minLon, maxLat, maxLon]: PoiRegion["bbox"]): number {
  return (maxLat - minLat) * (maxLon - minLon);
}

/** The smallest region whose area contains the point, or null. */
export function regionForPoint(lat: number, lon: number, regions: PoiRegion[] = POI_REGIONS): PoiRegion | null {
  const inside = regions.filter(({ bbox: [a, b, c, d] }) => lat >= a && lat <= c && lon >= b && lon <= d);
  return inside.sort((x, y) => area(x.bbox) - area(y.bbox))[0] ?? null;
}

/** Regions in the device's time zone (Intl timeZone, e.g. "America/Sao_Paulo"): a guess that needs no permission. */
export function regionsForTimeZone(tz: string, regions: PoiRegion[] = POI_REGIONS): PoiRegion[] {
  return regions.filter((r) => r.timeZones.includes(tz));
}

/** Catalog entries for the download manager (kind "corpus", format "poi-pack"). */
export function poiCatalogEntries(regions: PoiRegion[] = POI_REGIONS): CatalogModel[] {
  return regions.map((r) => ({
    id: `poi-${r.id}`,
    kind: "corpus",
    format: "poi-pack",
    label: r.name.en,
    filename: r.filename,
    sizeBytes: r.sizeBytes,
    sha256: r.sha256,
    sourceUrl: r.sourceUrl,
    license: POI_LICENSE,
    description: `${r.poiCount.toLocaleString("en-US")} places to eat and drink (${r.veganCount} tagged vegan), OpenStreetMap ${r.osmDate.slice(0, 10)}`,
    required: false,
    // Without the gazetteer, "restaurants in <city>" can't find the city (PL-1): installed with it.
    requires: [WORLD_PLACES_ID],
  }));
}

/** The world gazetteer as a catalog entry (fixed id), downloaded with any places pack. */
export function worldPlacesEntry(): CatalogModel {
  return {
    id: WORLD_PLACES_ID,
    kind: "corpus",
    format: "poi-pack",
    label: "World places (GeoNames)",
    filename: WORLD_PLACES.filename,
    sizeBytes: WORLD_PLACES.sizeBytes,
    sha256: WORLD_PLACES.sha256,
    sourceUrl: WORLD_PLACES.sourceUrl,
    license: WORLD_PLACES.license,
    description: `${WORLD_PLACES.places.toLocaleString("en-US")} cities and towns with 15,000+ people, to find places by name offline`,
    required: false,
  };
}

// Places packs and the gazetteer are installable (download or file import) wherever the catalog is read.
registerAssetProvider("poi", () => [...poiCatalogEntries(), worldPlacesEntry()]);

// ---- 1°×1° tiles (scripts/build-poi-world.mjs) ----

/** A tile as listed in the gazetteer's tile index. */
export interface PoiTile {
  id: string;
  sizeBytes: number;
  sha256: string;
  pois: number;
  vegan: number;
  osmDate: string;
  /** Hosted file, pinned to its upload commit; absent while the tile isn't hosted. */
  url?: string;
}

/** "t-N41E012" for the tile containing a point (south-west corner 41°N 12°E). */
export function tileIdOf(lat: number, lon: number): string {
  const la = Math.floor(lat);
  const lo = Math.floor(lon);
  return `t-${la >= 0 ? "N" : "S"}${String(Math.abs(la)).padStart(2, "0")}${lo >= 0 ? "E" : "W"}${String(Math.abs(lo)).padStart(3, "0")}`;
}

/** [minLat, minLon, maxLat, maxLon] of a tile id, or null if it isn't one. */
export function tileBbox(id: string): [number, number, number, number] | null {
  const m = id.match(/^t-([NS])(\d{2})([EW])(\d{3})$/);
  if (!m) return null;
  const lat = (m[1] === "N" ? 1 : -1) * Number(m[2]);
  const lon = (m[3] === "E" ? 1 : -1) * Number(m[4]);
  return [lat, lon, lat + 1, lon + 1];
}

/** Ids of the tiles a circle touches: the city's area for "I'm going to X" (1 to 4 tiles for a city). */
export function tileIdsFor(lat: number, lon: number, radiusKm: number): string[] {
  const dLat = radiusKm / 111.195;
  const dLon = dLat / Math.max(0.01, Math.cos((lat * Math.PI) / 180));
  const ids: string[] = [];
  for (let la = Math.floor(lat - dLat); la <= Math.floor(lat + dLat); la++) {
    for (let lo = Math.floor(lon - dLon); lo <= Math.floor(lon + dLon); lo++) {
      if (la >= -90 && la < 90) ids.push(tileIdOf(la, ((((lo + 180) % 360) + 360) % 360) - 180));
    }
  }
  return [...new Set(ids)];
}

/** Catalog entry of a tile (id "poi-t-N41E012", file "poi/t-N41E012.sqlite"). */
export function tileEntry(t: PoiTile): CatalogModel {
  return {
    id: `poi-${t.id}`,
    kind: "corpus",
    format: "poi-pack",
    label: `Places ${t.id.slice(2)}`,
    filename: `poi/${t.id}.sqlite`,
    sizeBytes: t.sizeBytes,
    sha256: t.sha256,
    sourceUrl: t.url ?? "",
    license: POI_LICENSE,
    description: `${t.pois.toLocaleString("en-US")} places to eat and drink (${t.vegan} tagged vegan), OpenStreetMap ${t.osmDate.slice(0, 10)}`,
    required: false,
    requires: [WORLD_PLACES_ID],
  };
}
