/**
 * English Wikipedia as 15 format-2 packs (scripts/build-wiki-pack.mjs, one per
 * FineWiki shard; docs/KNOWLEDGE_PACKS.md): catalog entries for the download
 * manager. The app searches every installed pack, so a phone can hold any
 * subset. Sizes, SHA-256 and counts are the measured build of 2026-09-26,
 * generated by scripts/wiki-en-catalog.mjs. No native imports.
 */
import type { CatalogModel } from "../models/manifest";
import { registerAssetProvider } from "../models/assetRegistry";

export interface WikiEnShard {
  /** 0-14, the FineWiki shard it was built from. */
  part: number;
  sizeBytes: number;
  sha256: string;
  /** Pinned to the upload commit on the Hugging Face dataset r4topunk/boar-packs. */
  sourceUrl: string;
  articles: number;
}

// <generated by scripts/wiki-en-catalog.mjs>
export const WIKI_EN_SHARDS: WikiEnShard[] = [
  {
    part: 0,
    sizeBytes: 1211727872,
    sha256: "89fc7c1cac60c09e61a636d001e9c5b2a2f3f08f6c10ac1150d2e0e9be53ab14",
    sourceUrl: "https://huggingface.co/datasets/r4topunk/boar-packs/resolve/6e9afe9658e0f933a36f233749f51967dd57fbe0/wiki/en/boar-wiki-en-00.sqlite",
    articles: 390522
  },
  {
    part: 1,
    sizeBytes: 1214562304,
    sha256: "8a8aa91b148cb8a8ceacfcf781e3e8f8b34674a770c940cd1af34c83b8869d99",
    sourceUrl: "https://huggingface.co/datasets/r4topunk/boar-packs/resolve/6e9afe9658e0f933a36f233749f51967dd57fbe0/wiki/en/boar-wiki-en-01.sqlite",
    articles: 421215
  },
  {
    part: 2,
    sizeBytes: 1197858816,
    sha256: "802799c868f790b12e910cdb8b07cc20b66005ab62c5a0238122827a657bc0b2",
    sourceUrl: "https://huggingface.co/datasets/r4topunk/boar-packs/resolve/6e9afe9658e0f933a36f233749f51967dd57fbe0/wiki/en/boar-wiki-en-02.sqlite",
    articles: 418631
  },
  {
    part: 3,
    sizeBytes: 1275125760,
    sha256: "f840226abf35d0d118f8d7c840710f5d2b85d67e8241b4054d0e81f7c7ebac9d",
    sourceUrl: "https://huggingface.co/datasets/r4topunk/boar-packs/resolve/6e9afe9658e0f933a36f233749f51967dd57fbe0/wiki/en/boar-wiki-en-03.sqlite",
    articles: 439892
  },
  {
    part: 4,
    sizeBytes: 1199259648,
    sha256: "af849afa078c43216ad0ac2f82643c88224e8ed8b6c16c5e42cabc89703edf8e",
    sourceUrl: "https://huggingface.co/datasets/r4topunk/boar-packs/resolve/6e9afe9658e0f933a36f233749f51967dd57fbe0/wiki/en/boar-wiki-en-04.sqlite",
    articles: 424238
  },
  {
    part: 5,
    sizeBytes: 1198260224,
    sha256: "e79d11552a58aaab507df4d01971778669795634d7026994a5bd435b47b48da2",
    sourceUrl: "https://huggingface.co/datasets/r4topunk/boar-packs/resolve/6e9afe9658e0f933a36f233749f51967dd57fbe0/wiki/en/boar-wiki-en-05.sqlite",
    articles: 430580
  },
  {
    part: 6,
    sizeBytes: 1174061056,
    sha256: "74caefe917f9ca999d9db95875605d9a580a6f74cf7988ebfaa7646a1cc066e2",
    sourceUrl: "https://huggingface.co/datasets/r4topunk/boar-packs/resolve/6e9afe9658e0f933a36f233749f51967dd57fbe0/wiki/en/boar-wiki-en-06.sqlite",
    articles: 418883
  },
  {
    part: 7,
    sizeBytes: 1213472768,
    sha256: "2455c805270ac04ecb921176f9110227aa5f1c05fbe7e14830ce13d57a68385b",
    sourceUrl: "https://huggingface.co/datasets/r4topunk/boar-packs/resolve/6e9afe9658e0f933a36f233749f51967dd57fbe0/wiki/en/boar-wiki-en-07.sqlite",
    articles: 403973
  },
  {
    part: 8,
    sizeBytes: 1190060032,
    sha256: "1bd7ef6a215196451042bcc346a4c6de4062f8e6f509b3d003bc3157d6540b48",
    sourceUrl: "https://huggingface.co/datasets/r4topunk/boar-packs/resolve/ce244fa65789d8628de0d979969b7d526f10d63f/wiki/en/boar-wiki-en-08.sqlite",
    articles: 410973
  },
  {
    part: 9,
    sizeBytes: 1191755776,
    sha256: "826e991935cfc90ef7f727f7d4916cd45f53ca93b64f247ca76f84a55ea64f1c",
    sourceUrl: "https://huggingface.co/datasets/r4topunk/boar-packs/resolve/ce244fa65789d8628de0d979969b7d526f10d63f/wiki/en/boar-wiki-en-09.sqlite",
    articles: 385785
  },
  {
    part: 10,
    sizeBytes: 1197711360,
    sha256: "734e44d8f34ce4a700a05f1607c2a1399465a10f7e21ba1e44ec2b7fc7d4f901",
    sourceUrl: "https://huggingface.co/datasets/r4topunk/boar-packs/resolve/ce244fa65789d8628de0d979969b7d526f10d63f/wiki/en/boar-wiki-en-10.sqlite",
    articles: 406962
  },
  {
    part: 11,
    sizeBytes: 1201504256,
    sha256: "47ab500ba03a92fa98c162351d1007c94bf4782324179aed5ed32c04c9530f58",
    sourceUrl: "https://huggingface.co/datasets/r4topunk/boar-packs/resolve/ce244fa65789d8628de0d979969b7d526f10d63f/wiki/en/boar-wiki-en-11.sqlite",
    articles: 386973
  },
  {
    part: 12,
    sizeBytes: 1205198848,
    sha256: "23ccdecc6b71b8ef1fd6f0d117ba6762b2c1dcc44bf60a838796bc5b4890cfc8",
    sourceUrl: "https://huggingface.co/datasets/r4topunk/boar-packs/resolve/ce244fa65789d8628de0d979969b7d526f10d63f/wiki/en/boar-wiki-en-12.sqlite",
    articles: 403088
  },
  {
    part: 13,
    sizeBytes: 1137795072,
    sha256: "189c1c011ebea6de20c6849ce3233ac723737fa31dae5c570028b42f73cbf24e",
    sourceUrl: "https://huggingface.co/datasets/r4topunk/boar-packs/resolve/ce244fa65789d8628de0d979969b7d526f10d63f/wiki/en/boar-wiki-en-13.sqlite",
    articles: 372746
  },
  {
    part: 14,
    sizeBytes: 1217855488,
    sha256: "abb0edb68c7792767a783b2d5bc5fcc1a6af1253c30c4f721e2cde3227985f34",
    sourceUrl: "https://huggingface.co/datasets/r4topunk/boar-packs/resolve/ce244fa65789d8628de0d979969b7d526f10d63f/wiki/en/boar-wiki-en-14.sqlite",
    articles: 410159
  }
];
// </generated>

export function wikiEnEntries(shards: WikiEnShard[] = WIKI_EN_SHARDS): CatalogModel[] {
  return shards.map((s) => {
    const nn = String(s.part).padStart(2, "0");
    return {
      id: `boar-wiki-en-${nn}`,
      kind: "corpus",
      format: "sqlite-pack",
      label: `English Wikipedia, part ${s.part + 1} of ${shards.length}`,
      filename: `corpus/boar-wiki-en-${nn}.sqlite`,
      sizeBytes: s.sizeBytes,
      sha256: s.sha256,
      sourceUrl: s.sourceUrl,
      license: "CC BY-SA 4.0 (Wikipedia)",
      description: `${s.articles.toLocaleString("en-US")} Wikipedia articles (full text for the most-read, leads for the rest), searchable offline`,
      required: false,
    };
  });
}

/** English Wikivoyage as its own pack (the Wikipedia shards carry no Wikivoyage). */
export const WIKIVOYAGE_EN = {
  id: "boar-wikivoyage-en",
  filename: "corpus/boar-wikivoyage-en.sqlite",
  sizeBytes: 351092736,
  sha256: "ff8595e32f56b8b84e20464afd8bf88532d47d2d82d799e3df8489440004b66e",
  /** Pinned to the upload commit on the Hugging Face dataset r4topunk/boar-packs. */
  sourceUrl: "https://huggingface.co/datasets/r4topunk/boar-packs/resolve/9557c7b2a50a1c37fdf36d41db4cd0fdc8c33c0b/wiki/en/boar-wikivoyage-en.sqlite",
  guides: 34002,
};

export function wikivoyageEnEntry(): CatalogModel {
  return {
    id: WIKIVOYAGE_EN.id,
    kind: "corpus",
    format: "sqlite-pack",
    label: "English Wikivoyage",
    filename: WIKIVOYAGE_EN.filename,
    sizeBytes: WIKIVOYAGE_EN.sizeBytes,
    sha256: WIKIVOYAGE_EN.sha256,
    sourceUrl: WIKIVOYAGE_EN.sourceUrl,
    license: "CC BY-SA 4.0 (Wikivoyage)",
    description: `${WIKIVOYAGE_EN.guides.toLocaleString("en-US")} travel guides (see, do, eat, drink, stay safe), searchable offline`,
    required: false,
  };
}

registerAssetProvider("wiki-en", () => [...wikiEnEntries(), wikivoyageEnEntry()]);
